<Project>
    <PropertyGroup Condition="'$(TargetFramework)' == '' And '$(TargetFrameworks)' == ''">
        <!-- Only set a default target framework if none is set (either as a single value or multiple values, see dotnet/msbuild#7856) -->
        <TargetFramework>net9.0</TargetFramework>
    </PropertyGroup>

    <PropertyGroup>
        <OutputPath>bin/$(TargetFramework)/$(Configuration)/</OutputPath>
        <LangVersion>latest</LangVersion>
		
        <Company>TrinityCore</Company>
        <Copyright>Copyright © 2010-2024</Copyright>
        <PackageProjectUrl>https://www.trinitycore.org/</PackageProjectUrl>
        <NeutralLanguage>en</NeutralLanguage>
        <RepositoryUrl>https://github.com/TrinityCore/WowPacketParser</RepositoryUrl>
        <RepositoryType>GitHub</RepositoryType>
        <Authors>TrinityCore</Authors>

        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
        <AppendTargetFrameworkToOutputPath>true</AppendTargetFrameworkToOutputPath>
    </PropertyGroup>
</Project>
